In [2]:
import pandas as pd
import numpy as np

In [3]:
F = pd.read_csv('Female-Names.csv')
M = pd.read_csv('Male-Names.csv')


In [4]:
print(F.tail(5))
print(F.shape)
print(M.shape)


                            name gender    race
15377                 saroj devi      f  indian
15378              naina @ geeta      f  indian
15379  manju d/0 baboo lal jatav      f  indian
15380                    shivani      f  indian
15381                      nayna      f  indian
(15382, 3)
(14845, 3)


In [5]:

print(M.tail(5))

                      name gender    race
14840               buddha      m  indian
14841               mukesh      m  indian
14842                 monu      m  indian
14843  govind prasad shahu      m  indian
14844               deepak      m  indian


In [6]:
df = pd.concat([M,F])

In [7]:
df.shape

(30227, 3)

In [8]:
df.tail(20)

name gender    race
15362                smt. sabnam      f  indian
15363                   narayani      f  indian
15364                    manisha      f  indian
15365                      bimla      f  indian
15366                      neetu      f  indian
15367                   priyanka      f  indian
15368                      priti      f  indian
15369                     kavita      f  indian
15370                km. bhavna,      f  indian
15371                  कु0 भावना      f  indian
15372                      anjum      f  indian
15373                 miss reena      f  indian
15374                      pooja      f  indian
15375                      rakhi      f  indian
15376                   musarrat      f  indian
15377                 saroj devi      f  indian
15378              naina @ geeta      f  indian
15379  manju d/0 baboo lal jatav      f  indian
15380                    shivani      f  indian
15381                      nayna      f  indian

In [1]:
char2idx = {}
char_set =[' ', '.','END', 'a', 'c', 'b', 'e', 'd', 'g', 'f', 'i', 'h', 'k', 'j', 'm', 'l', 'o', 'n', 'q', 'p', 's', 'r', 'u', 't', 'w', 'v', 'y', 'x', 'z'] 
index = 0
for ch in char_set:
  char2idx[ch] = index
  index += 1

29


In [10]:
def should_keep(word):
  if len(word) > 19:
    return False
  for ch in word:
    if ch not in set(char_set):
      return False
  return True

In [11]:
def clean(word):
  word = str(word)
  char_set = [' ', '.','END', 'a', 'c', 'b', 'e', 'd', 'g', 'f', 'i', 'h', 'k', 'j', 'm', 'l', 'o', 'n', 'q', 'p', 's', 'r', 'u', 't', 'w', 'v', 'y', 'x', 'z']    
  name = word.lower()
  name = name[:19]
  if should_keep(name):
    return name
  else:
    return None

In [12]:
df.name = df.name.apply(lambda x: clean(x))

In [13]:
df = df.dropna()

In [14]:
df.tail(5)

name gender    race
15375       rakhi      f  indian
15376    musarrat      f  indian
15377  saroj devi      f  indian
15380     shivani      f  indian
15381       nayna      f  indian

In [15]:
df.head(5)

name gender    race
0          barjraj      m  indian
1     ramdin verma      m  indian
2  sharat chandran      m  indian
3  birender mandal      m  indian
4             amit      m  indian

In [16]:
max_word_len = 20
def convert_one_hot(word):
  word_chars = []
  
  for ch in word:
    one_hot_vec = np.zeros(len(char_set),)
    one_hot_vec[char2idx[ch]] = 1
    word_chars.append(one_hot_vec)
    
  for _ in range(max_word_len - len(word)):
    one_hot_vec = np.zeros(len(char_set),)
    one_hot_vec[char2idx['END']] = 1
    word_chars.append(one_hot_vec)
  
  word_chars = np.array(word_chars)
  return word_chars

In [17]:
# [20*29]

In [18]:
words = []
labels = []
for n , g in df.drop('race', axis=1).itertuples(index=False):
  words.append(convert_one_hot(n))
  labels.append(g)
  

In [19]:
words[0]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [20]:
words = np.array(words)
labels = np.array(labels)

In [21]:
words.shape

(28363, 20, 29)

In [22]:
from sklearn.preprocessing import OneHotEncoder
ohe =  OneHotEncoder()
y = ohe.fit_transform(labels.reshape(-1, 1)).todense()

In [23]:
type(y)

numpy.matrix

In [24]:
y[:10]

matrix([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]])

In [25]:

from keras.models import Sequential
from keras.layers import LSTM, Dropout, Dense

Using TensorFlow backend.


In [26]:
model = Sequential()
model.add(LSTM(64, input_shape = (20, 29), return_sequences=True))
model.add(LSTM(64))
model.add(Dropout(.3))
model.add(Dense(2, activation='sigmoid'))
model.summary()

W0927 09:25:00.069158 140179986659136 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0927 09:25:00.366168 140179986659136 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0927 09:25:00.412659 140179986659136 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0927 09:25:01.178333 140179986659136 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0927 09:25:01.197494 

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 20, 64)            24064     
_________________________________________________________________
lstm_2 (LSTM)                (None, 64)                33024     
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 130       
Total params: 57,218
Trainable params: 57,218
Non-trainable params: 0
_________________________________________________________________


In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(words, y, test_size=0.33, random_state=42)

In [28]:
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['acc'])

W0927 09:25:01.868818 140179986659136 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0927 09:25:01.900039 140179986659136 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [29]:
model.fit(X_train, y_train, epochs=10)

W0927 09:25:02.402517 140179986659136 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/10
19003/19003 [==============================] - 17s 898us/step - loss: 0.5181 - acc: 0.7446
Epoch 2/10
19003/19003 [==============================] - 14s 717us/step - loss: 0.3998 - acc: 0.8266
Epoch 3/10
19003/19003 [==============================] - 14s 725us/step - loss: 0.3491 - acc: 0.8573
Epoch 4/10
19003/19003 [==============================] - 14s 733us/step - loss: 0.3080 - acc: 0.8795
Epoch 5/10
19003/19003 [==============================] - 14s 735us/step - loss: 0.2818 - acc: 0.8921
Epoch 6/10
19003/19003 [==============================] - 15s 791us/step - loss: 0.2654 - acc: 0.9021
Epoch 7/10
19003/19003 [==============================] - 15s 784us/step - loss: 0.2479 - acc: 0.9091
Epoch 8/10
19003/19003 [==============================] - 15s 815us/step - loss: 0.2333 - acc: 0.9163
Epoch 9/10
19003/19003 [==============================] - 15s 782us/step - loss: 0.2232 - acc: 0.9219
Epoch 10/10
19003/19003 [==============================] - 15s 783us/step - loss: 

In [30]:
model.evaluate(X_test, y_test)

9360/9360 [==============================] - 2s 184us/step


[0.21677350952075078, 0.9253205128205129]

In [35]:
name = 'mona x'
model.predict(convert_one_hot(name).reshape(1, 20, 29))

array([[0.9373003 , 0.02872636]], dtype=float32)

In [33]:
name = 'apoorv varshney'
model.predict(convert_one_hot(name).reshape(1, 20, 29))

array([[0.02170081, 0.8933456 ]], dtype=float32)

In [36]:
#LSTM will always give flatten output
model.save("model.h5")
print("Saved model to disk")


Saved model to disk


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 20, 64)            24064     
_________________________________________________________________
lstm_2 (LSTM)                (None, 64)                33024     
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 130       
Total params: 57,218
Trainable params: 57,218
Non-trainable params: 0
_________________________________________________________________
%s: %.2f%% [[0.02170081 0.8933456 ]]
